import type { Metadata } from 'next';
import './globals.css';
import Header from 'components/Header';
import Footer from 'components/Footer';
import { ThemeProvider } from 'components/ThemeProvider';

export const metadata: Metadata = {
    title: 'Kimi | FE',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko" suppressHydrationWarning>
            <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
                <body>
                    <main className="flex flex-col min-h-screen text-neutral-900 dark:bg-[#111111] dark:text-white ">
                        <Header />
                        {children}
                    </main>
                </body>
                <Footer />
            </ThemeProvider>
        </html>
    );
}
