import type { Metadata } from 'next';
import './globals.css';
import Header from 'components/Header';

export const metadata: Metadata = {
    title: 'Kimi | FE',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="max-w-screen-md min-w-[320px] mx-auto">
                <Header />
                {children}
            </body>
        </html>
    );
}
